<a href="https://colab.research.google.com/github/Sonam-rizz/2461838_SonamYangzom/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Problem 1

#1
a = np.zeros((2, 2))
print(a)

#2
b = np.ones((4,2))
print(b)

#3
c = np.full((4,4),2)
print(c)

#4
d = np.zeros_like(a)
print(d)

#5
e = np.ones_like(b)
print(e)

#6
new_list = [1,2,3,4]
f = np.array(new_list)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


In [ ]:
#Problem 2

#1
g = np.arange(10,50)
print(g)

#2
h = np.arange(0,9)

matrix = h.reshape(3,3)
print(matrix)

#3
i = np.eye(3)
print(i)

#4
j = np.random.random(30)
print(j)
mean = j.mean()
print(mean)

#5
k = np.random.random((10,10))
print(k)
print("Max Value", k.max())
print("Min Value", k.min())

#6
l = np.zeros(10)
print(l)
l[4] = 1
print(l)

#7
arr = [1,2,0,0,4,0]
arr_np = np.array(arr)
print(arr_np)
reversed = np.flip(arr_np)
print(reversed)

#8
m = np.zeros((5,5), dtype=int)
m[0, :]= 1 #top row
m[-1, :]= 1 #bottom row
m[:, 0]= 1  #left column
m[:, -1]= 1 #right column
print(m)

#9
n = np.zeros((8,8), dtype=int)
n[1::2, ::2] = 1 #row: 1,3,5,7 column: 0,2,4,6
n[::2, 1::2] = 1#row 0,2,4,6 column: 1,3,5,7
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.35151017 0.65696655 0.91948974 0.46131726 0.0409776  0.33336524
 0.30785825 0.24824369 0.41120747 0.32627907 0.27370575 0.47869295
 0.07393933 0.27863033 0.90483212 0.27841782 0.99093865 0.09686022
 0.94387466 0.83898295 0.58846239 0.45292931 0.7149378  0.52646288
 0.73526991 0.32319867 0.99062733 0.66361633 0.70519071 0.41687764]
0.5111220931213898
[[9.05049269e-01 5.98834343e-01 3.58658764e-01 3.11456223e-01
  2.33194470e-01 7.40191381e-01 2.08644625e-01 1.92501848e-01
  8.64119695e-01 8.26094688e-01]
 [1.46298652e-01 1.51619630e-01 9.59615159e-01 6.52520855e-01
  7.41177405e-01 4.72375403e-03 9.19222934e-01 3.61163337e-03
  8.98114651e-01 4.66538092e-01]
 [7.76095382e-01 2.52080815e-01 2.55849493e-01 2.47631728e-01
  3.46051137e-01 4.43484601e-01 6.09527591e-01 2.64468923e-01
  9.95041260e-02 4.

In [ ]:
#Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

add_1= x + y
add_2 = v + w
print(add_1)
print(add_2)

sub_1 = x - y
sub_2 = v - w
print(sub_1)
print(sub_2)

multiplication = x * 2
multiplication_1 = w * 9
print(multiplication)
print(multiplication_1)

x_square = x ** 2
print(x_square)
y_square = y ** 2
print(y_square)
v_square = v ** 2
print(v_square)
w_square = w ** 2
print(w_square)

V_W = np.dot(v, w)
print("Dot Product between v and w",V_W)

X_Y = np.dot(x, y)
print("Dot Product between x and y \n", X_Y)

row_concat = np.concatenate((x,y), axis=0)
print(row_concat)

column_concat = np.vstack((v,w))
print(column_concat)

# concat_xv = np.concatenate((x,v), axis=0)
# print(concat_xv)
#all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
[[ 2  4]
 [ 6 10]]
[ 99 108]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
Dot Product between v and w 219
Dot Product between x and y 
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
#Problem 4

#1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

I = np.eye(2, dtype=int)

A_inv = np.linalg.inv(A)
AdotA_inv = np.dot(A, A_inv)

AdotA_inv_int = np.round(AdotA_inv).astype(int)
print(AdotA_inv_int)

if np.array_equal(AdotA_inv_int, I):
    print("True")
else:
    print(False)

#2
AdotB = np.dot(A,B)
BdotA = np.dot(B,A)

print(AdotB)
print(BdotA)

if np.array_equal(AdotB, BdotA):
    print("Equal")
else:
    print("Not Equal")


#3
AdotB = np.dot(A,B)
AdotB_T = AdotB.T

B_T = B.T
A_T = A.T
B_TdotA_T = np.dot(B_T, A_T)

if np.array_equal(AdotB_T, B_TdotA_T):
    print("Equal: (AB)^T = B^T A^T")
else:
    print("NotEqual")

[[1 0]
 [0 1]]
True
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Not Equal
Equal: (AB)^T = B^T A^T


In [ ]:
#Linear Equations
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-3],[9]])

Ainv = np.linalg.inv(A)
x = np.dot(Ainv, B)

print(x)

[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
#Element-Wise Addition

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list addition:", end_time - start_time, "seconds")

arr1 = np.array(n)
arr2 = np.array(n)

start_time = time.time()
arr_sum = arr1 + arr2
end_time = time.time()
print("Time taken for NumPy array addition:", end_time - start_time, "seconds")

Time taken for Python list addition: 0.014299154281616211 seconds
Time taken for NumPy array addition: 0.00013184547424316406 seconds


In [ ]:
#Element wise Multiplication

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list multiplication:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
arr_product = arr1 * arr2
end_time = time.time()
print("Time taken for NumPy array multiplication:", end_time - start_time, "seconds")

Time taken for Python list multiplication: 0.013377666473388672 seconds
Time taken for NumPy array multiplication: 0.0006232261657714844 seconds


In [ ]:
#Dot Product

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(n))
end_time = time.time()
print("Time taken for Python list dot product:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
dot_arr = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for NumPy array dot product:", end_time - start_time, "seconds")

Time taken for Python list dot product: 0.022482633590698242 seconds
Time taken for NumPy array dot product: 0.0004017353057861328 seconds


In [ ]:
import time
import numpy as np
import random

n = 1000

arr1 = np.random.randint(0, 10, size=(n,n))
arr2 = np.random.randint(0, 10, size=(n,n))

start_time = time.time()
result_np = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for Numpy Array Matrix Multiplication", end_time - start_time , "seconds")

Time taken for Numpy Array Matrix Multiplication 2.275843620300293 seconds
